### ISSUE TITLE
Font-size changing and cookie

### ISSUE THREAD

**Issue by Letoile** [Rinamika/cecutient#4]
Улучшить (исправить? :)) алгоритм изменения размера шрифта и сохранение значения инкремента в куки:
- Сейчас увеличивается шрифт основного контейнера + последовательно все внутренние элементы => неправильный (увеличенный) размер
- Если размер шрифта выходит за установленный лимит, менять значение инкремента в куки на максимальный/минимальный (либо сразу проверять инкремент, а не размер)

см. проект библиотеки

**Comment by Letoile** [comment]
А так же
- Заменить тупое удаление атрибута style на удаление только данных о font-size и line-height
  `$(this).css("fontSize", "").css("lineHeight", "");`

**Comment by POPSuL** [comment]
Что с решением это проблемы?

**Comment by Letoile** [comment]
Решена в одном проекте, надо переносить, но не до того

**Comment by Letoile** [comment]
@POPSuL, таки доделала
